[package]
name = "cm-rust"
version = "0.1.0"
authors = ["Alexander Elvers"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.1.0"
sdl2 = "0.32.2"
